Repository goormthon-Univ/TEAM_1, pull requests merged in 2023-11, with the labels that each got.

#6 프로젝트 초기 환경 설정
  build.gradle
  src/main/resources/application-local.yml
  src/main/resources/application-prod.yml
  src/main/resources/application.properties
  src/main/resources/application.yml
Labels: ✨ Feature

#8 예외 처리 핸들러 구현
  src/main/java/today/seasoning/seasoning/common/exception/CustomException.java
  src/main/java/today/seasoning/seasoning/common/exception/ErrorResponse.java
  src/main/java/today/seasoning/seasoning/common/exception/GlobalExceptionHandler.java
Labels: ✨ Feature

#9 CORS 설정
  src/main/java/today/seasoning/seasoning/common/config/CorsConfig.java
  src/main/java/today/seasoning/seasoning/common/config/SecurityConfig.java
Labels: ✨ Feature

#10 JWT 설정
  build.gradle
  src/main/java/today/seasoning/seasoning/SeasoningApplication.java
  src/main/java/today/seasoning/seasoning/common/BaseTimeEntity.java
  src/main/java/today/seasoning/seasoning/common/UserPrincipal.java
  src/main/java/today/seasoning/seasoning/common/config/JwtFilter.java
  src/main/java/today/seasoning/seasoning/common/config/SecurityConfig.java
  src/main/java/today/seasoning/seasoning/common/enums/LoginType.java
  src/main/java/today/seasoning/seasoning/common/util/JwtUtil.java
Labels: ✨ Feature

#14 오늘의 운세 조회 구현
  src/main/java/today/seasoning/seasoning/fortune/controller/FortuneController.java
  src/main/java/today/seasoning/seasoning/fortune/domain/Fortune.java
  src/main/java/today/seasoning/seasoning/fortune/domain/FortuneRepository.java
  src/main/java/today/seasoning/seasoning/fortune/service/FortuneService.java
Labels: ✨ Feature

#17 deploy.yml 문법 오류 해결
  .github/workflows/deploy.yml
Labels: 🐛 Bug

#22 JWT 필터 기능 변경
  src/main/java/today/seasoning/seasoning/common/UserPrincipal.java
  src/main/java/today/seasoning/seasoning/common/config/JwtFilter.java
  src/main/java/today/seasoning/seasoning/common/config/SecurityConfig.java
Labels: ✨ Feature

#28 친구 기능 구현 : 친구 신청, 친구 목록 조회
  src/main/java/today/seasoning/seasoning/SeasoningApplication.java
  src/main/java/today/seasoning/seasoning/article/controller/ArticleController.java
  src/main/java/today/seasoning/seasoning/article/domain/Article.java
  src/main/java/today/seasoning/seasoning/article/domain/ArticleImage.java
  src/main/java/today/seasoning/seasoning/article/domain/ArticleImageRepository.java
  src/main/java/today/seasoning/seasoning/article/domain/ArticleLike.java
  src/main/java/today/seasoning/seasoning/article/domain/ArticleLikeRepository.java
  src/main/java/today/seasoning/seasoning/article/domain/ArticleRepository.java
  src/main/java/today/seasoning/seasoning/article/dto/ArticleImageDto.java
  src/main/java/today/seasoning/seasoning/article/dto/RegisterArticleCommand.java
  src/main/java/today/seasoning/seasoning/article/dto/RegisterArticleWebRequest.java
  src/main/java/today/seasoning/seasoning/article/service/RegisterArticleService.java
  src/main/java/today/seasoning/seasoning/common/util/SolarTermUtil.java
  src/main/java/today/seasoning/seasoning/common/util/TsidUtil.java
  src/main/java/today/seasoning/seasoning/friendship/controller/FriendshipController.java
  src/main/java/today/seasoning/seasoning/friendship/domain/Friendship.java
  src/main/java/today/seasoning/seasoning/friendship/domain/FriendshipRepository.java
  src/main/java/today/seasoning/seasoning/friendship/dto/FindUserFriendsResult.java
  src/main/java/today/seasoning/seasoning/friendship/dto/ToUserAccountIdDto.java
  src/main/java/today/seasoning/seasoning/friendship/service/FindUserFriendsService.java
  src/main/java/today/seasoning/seasoning/friendship/service/RequestFriendshipService.java
  src/main/java/today/seasoning/seasoning/user/domain/User.java
  src/main/java/today/seasoning/seasoning/user/domain/UserRepository.java
Labels: ✨ Feature

#31 사용자 프로필 수정 기능 수정
  src/main/java/today/seasoning/seasoning/user/domain/User.java
  src/main/java/today/seasoning/seasoning/user/service/UserService.java
Labels: ♻️ Refactor

#33 사용자 서비스 트랜잭션 어노테이션 추가
  src/main/java/today/seasoning/seasoning/user/service/UserService.java
Labels: ♻️ Refactor

#34 친구 기능 구현 : 친구 수락, 거절, 취소, 삭제
  src/main/java/today/seasoning/seasoning/friendship/controller/FriendshipController.java
  src/main/java/today/seasoning/seasoning/friendship/domain/FriendshipRepository.java
  src/main/java/today/seasoning/seasoning/friendship/service/AcceptFriendshipService.java
  src/main/java/today/seasoning/seasoning/friendship/service/CancelFriendshipService.java
  src/main/java/today/seasoning/seasoning/friendship/service/DeclineFriendshipService.java
  src/main/java/today/seasoning/seasoning/friendship/service/DeleteFriendshipService.java
Labels: ✨ Feature

#37 기록장 수정 및 삭제 기능 구현 (파일 처리 x)
  src/main/java/today/seasoning/seasoning/article/controller/ArticleController.java
  src/main/java/today/seasoning/seasoning/article/domain/Article.java
  src/main/java/today/seasoning/seasoning/article/dto/UpdateArticleDto.java
  src/main/java/today/seasoning/seasoning/article/dto/UpdateArticleImageDto.java
  src/main/java/today/seasoning/seasoning/article/service/DeleteArticleService.java
  src/main/java/today/seasoning/seasoning/article/service/UpdateArticleService.java
Labels: ✨ Feature

#40 기록장 이미지 업로드 및 삭제 기능 구현
  build.gradle
  src/main/java/today/seasoning/seasoning/article/controller/ArticleController.java
  src/main/java/today/seasoning/seasoning/article/domain/Article.java
  src/main/java/today/seasoning/seasoning/article/domain/ArticleImage.java
  src/main/java/today/seasoning/seasoning/article/dto/ArticleImageDto.java
  src/main/java/today/seasoning/seasoning/article/dto/FindArticleImageResult.java
  src/main/java/today/seasoning/seasoning/article/dto/FindArticleResult.java
  src/main/java/today/seasoning/seasoning/article/dto/RegisterArticleDto.java
  src/main/java/today/seasoning/seasoning/article/dto/UpdateArticleCommand.java
  src/main/java/today/seasoning/seasoning/article/dto/UpdateArticleDto.java
  src/main/java/today/seasoning/seasoning/article/dto/UpdateArticleImageDto.java
  src/main/java/today/seasoning/seasoning/article/service/DeleteArticleService.java
  src/main/java/today/seasoning/seasoning/article/service/FindArticleService.java
  src/main/java/today/seasoning/seasoning/article/service/RegisterArticleService.java
  src/main/java/today/seasoning/seasoning/article/service/UpdateArticleService.java
  src/main/java/today/seasoning/seasoning/common/aws/S3Service.java
  src/main/java/today/seasoning/seasoning/common/aws/UploadFileInfo.java
  src/main/java/today/seasoning/seasoning/common/config/S3Config.java
  src/main/resources/application.yml
Labels: ✨ Feature

#41 친구 기능 구현: 검색
  src/main/java/today/seasoning/seasoning/common/enums/FriendshipStatus.java
  src/main/java/today/seasoning/seasoning/friendship/controller/FriendshipController.java
  src/main/java/today/seasoning/seasoning/friendship/dto/SearchFriendResult.java
  src/main/java/today/seasoning/seasoning/friendship/service/SearchFriendshipService.java
Labels: ✨ Feature

#54 콜라주 조회 기능 구현
  src/main/java/today/seasoning/seasoning/article/controller/ArticleController.java
  src/main/java/today/seasoning/seasoning/article/dto/FindCollageResult.java
  src/main/java/today/seasoning/seasoning/article/service/FindCollageService.java
Labels: ✨ Feature

#55 프로필 수정 기능 변경
  src/main/java/today/seasoning/seasoning/user/controller/UserController.java
  src/main/java/today/seasoning/seasoning/user/domain/User.java
  src/main/java/today/seasoning/seasoning/user/dto/UpdateUserProfile.java
  src/main/java/today/seasoning/seasoning/user/dto/UpdateUserProfileCommand.java
  src/main/java/today/seasoning/seasoning/user/dto/UpdateUserProfileDto.java
  src/main/java/today/seasoning/seasoning/user/service/FindUserProfileService.java
  src/main/java/today/seasoning/seasoning/user/service/UpdateUserProfileService.java
  src/main/java/today/seasoning/seasoning/user/service/ValidateAccountIdUsability.java
  src/main/java/today/seasoning/seasoning/user/service/ValidateAccountIdUsabilityImpl.java
Labels: ✨ Feature

#58 친구 기록장 목록 조회 기능 구현
  src/main/java/today/seasoning/seasoning/article/controller/ArticleController.java
  src/main/java/today/seasoning/seasoning/article/dto/FindMyFriendsArticlesResult.java
  src/main/java/today/seasoning/seasoning/article/dto/FriendArticleDto.java
  src/main/java/today/seasoning/seasoning/article/dto/UserProfileDto.java
  src/main/java/today/seasoning/seasoning/article/service/FindMyFriendsArticlesService.java
Labels: ✨ Feature

#61 알림 기능 구현
  src/main/java/today/seasoning/seasoning/article/service/ArticleLikeService.java
  src/main/java/today/seasoning/seasoning/common/util/EntitySerializationUtil.java
  src/main/java/today/seasoning/seasoning/common/util/SolarTermUtil.java
  src/main/java/today/seasoning/seasoning/friendship/service/AcceptFriendshipService.java
  src/main/java/today/seasoning/seasoning/notification/controller/NotificationController.java
  src/main/java/today/seasoning/seasoning/notification/domain/Notification.java
  src/main/java/today/seasoning/seasoning/notification/domain/NotificationRepository.java
  src/main/java/today/seasoning/seasoning/notification/domain/NotificationType.java
  src/main/java/today/seasoning/seasoning/notification/dto/FindNotificationCommand.java
  src/main/java/today/seasoning/seasoning/notification/dto/NotificationDto.java
  src/main/java/today/seasoning/seasoning/notification/dto/RegisterNotificationCommand.java
  src/main/java/today/seasoning/seasoning/notification/service/NotificationService.java
  src/main/java/today/seasoning/seasoning/user/controller/UserController.java
  src/main/java/today/seasoning/seasoning/user/dto/SocialUserProfileDto.java
  src/main/java/today/seasoning/seasoning/user/dto/UserProfile.java
  src/main/java/today/seasoning/seasoning/user/dto/UserProfileDto.java
  src/main/java/today/seasoning/seasoning/user/service/FindUserProfileService.java
  src/main/java/today/seasoning/seasoning/user/service/KakaoLoginService.java
  src/main/java/today/seasoning/seasoning/user/service/port/kakao/FetchKakaoUserProfile.java
  src/main/java/today/seasoning/seasoning/user/service/port/kakao/FetchKakaoUserProfileImpl.java
Labels: ✨ Feature

#62 feat: 소셜 로그인 시, 회원가입 여부를 나타내는 Is-First 헤더 추가
  src/main/java/today/seasoning/seasoning/user/controller/OauthController.java
  src/main/java/today/seasoning/seasoning/user/dto/LoginResultDto.java
  src/main/java/today/seasoning/seasoning/user/service/KakaoLoginService.java
Labels: ✨ Feature

#64 CORS 설정 오류 해결
  src/main/java/today/seasoning/seasoning/common/config/CorsConfig.java
Labels: 🐛 Bug

#66 이미지 저장용 S3 버킷에 CDN 적용
  src/main/java/today/seasoning/seasoning/common/aws/S3Service.java
Labels: ♻️ Refactor
